version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestTemp1Project
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestTemp1Project
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: SIQA_Origin
  gitServerName: testInternalGit
  gitUrl: https://github.webmethods.io/shih
  gitUsername: poan
  gitBranch: main
